version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - service

  service:
    build:
      context: ./service
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
